monitor:
  name: 7T
  width: 69  # width of monitor (in cm)
  distance: 225  # distance of participant from monitor (in cm)
  gamma: 1  # specific value for gamma correction
  verbose: True

window:
  units: pix
  size: [1920,1080]

eyetracker:
  address: '100.1.1.1'
  dot_size: 0.1  # in deg
  options:
    calibration_type: HV5

stimuli:
  fix_radius: 2.5
  fix_color: 0.5
  sound_volume: 1.0

design:
  start_duration: 24
  end_duration: 15
  stim_duration: 2.2

various:
  piechart_width: 1
  text_width: 250
  text_height: 25
  buttons: ['b', 'j', 'k', 'l', 'semicolon']
  button_size: 2
